name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2

    - name: Build with Gradle
      # הפקודה הזו מוצאת את קובץ ה-settings ובונה משם אוטומטית
      run: |
        SETTINGS_PATH=$(find . -name "settings.gradle" -print -quit)
        SETTINGS_DIR=$(dirname "$SETTINGS_PATH")
        gradle assembleDebug -p "$SETTINGS_DIR"
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-debug-apk
        path: "**/app/build/outputs/apk/debug/app-debug.apk"
